apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: customer-details-gateway
  namespace: default
  labels:
    app.kubernetes.io/part-of: customer-details
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8090"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.name: customer-details-gateway
spec:
  observability:
    metrics:
      prometheus:
        enabled: true
  count: 1
  api:
    title: Customer Details APIs
    description: Tanzu Curated API Demo
    version: 0.0.1
    groupId: customer-details-management
    serverUrl: 'https://customer-details.a3.fynesy.com'
    cors:
      allowedOrigins:
      - https://api-portal.a3.fynesy.com
      - https://tap-gui.a3.fynesy.com
      allowedMethods:
      - "GET"
      - "PUT"
      - "POST"
      allowedHeaders:
      - '*'
  serviceAccount:
    name: tdemo-gateway-svc-acc
  extensions:
    secretsProviders:
    - name: vault-api-keys
      vault:
        roleName: api-portal-role
        path: api-portal-for-vmware-tanzu
    filters:
      apiKey:
        enabled: true
        secretsProviderName: vault-api-keys

