apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  annotations:
    classclaims.services.apps.tanzu.vmware.com/xrd-name: xpostgresqlinstances.bitnami.database.tanzu.vmware.com
  finalizers:
  - classclaims.services.apps.tanzu.vmware.com/provision-finalizer
  name: hobby-database
  namespace: default
spec:
  classRef:
    name: postgresql-unmanaged
  parameters: {}
