apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: si1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: si1
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tfynes-pivotal/si1
      ref:
        branch: main
