apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdemo-gateway-cert
  namespace: default
spec:
  dnsNames:
  - tdemo.a3.fynesy.com
  secretName: taptlscert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
